export const REMOVE_USER_DATA = 'REMOVE_USER_DATA';
export const SAVE_USER_DATA = 'SAVE_USER_DATA';
export const SET_LOADING = 'SET_LOADING';
export const SAVE_SETTINGS = 'SAVE_SETTINGS';
export const UPDATE_COLLECTED_DATA = 'UPDATE_COLLECTED_DATA';
export const UPDATE_PERSONAL_DATA = 'UPDATE_PERSONAL_DATA';
export const UPDATE_WIZARD_SCEEN = 'UPDATE_WIZARD_SCEEN';
